Readme facelift
paule96/paule96.DotNetTemplate.GitIgnore pull request #3
Opened 2018-08-30 09:00 UTC by abeckDev

Made some minor changes to the structure of the readme.
Changed some formulations which sounds kind of confusing for me.

2018-08-30 17:30 UTC, paule96 requested changes
thanks for your feedback. It would be great if you can fix the comments. 👍

2018-08-30 17:30 UTC, paule96 commented on Readme.md
> +# dotnet new GitIgnoreTemplate
maybe we would change this to the real command.
dotnet new ignore

2018-08-30 17:30 UTC, paule96 commented on Readme.md
> +1. Install the template on your system
remove this line. This is no longer needed.

2018-08-30 17:30 UTC, paule96 commented on Readme.md
> +2. Get a list of available .gitignore templates
start here with 1.

2018-08-30 17:30 UTC, paule96 commented on Readme.md
> +2. Get a list of available .gitignore templates
Maybe we start here with a little headline. Like using or something like this

2018-08-30 17:30 UTC, paule96 commented on Readme.md
> +dotnet new --install paule96.DotNetTemplate.GitIgnore
please revert this because the dotnet communtiy knows -i better then install. see [here](https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new)

2018-08-30 17:30 UTC, paule96 commented on Readme.md
> +Follow theese steps to buidl the template from scratch on your own.
typo in build

2018-09-03 11:28 UTC, abeckDev commented on Readme.md
> +# dotnet new GitIgnoreTemplate
I would not change this. Because just ignore as the name in my opinion is to general.

2018-09-03 11:33 UTC, abeckDev commented on Readme.md
> +dotnet new --install paule96.DotNetTemplate.GitIgnore
Am I right?

First remove a Line and then revert its content? ^^

2018-09-13 11:33 UTC, abeckDev commented on Readme.md
> +1. Install the template on your system
Done

2018-09-13 11:33 UTC, abeckDev commented on Readme.md
> +dotnet new --install paule96.DotNetTemplate.GitIgnore
My mistake is changed now

2018-09-13 11:35 UTC, abeckDev commented
Updated suggestions. 

Please review @paule96

2018-09-14 11:19 UTC, paule96 approved these changes

2018-09-14 11:19 UTC, merged